In [35]:
import numpy as np

In [36]:
# --- 3.1: 1D NumPy Arrays ---
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [37]:
arr = np.array(list)
print(arr)

[20 27  9 12 31 17  4 50 39 35]


In [38]:
print(arr*5)

[100 135  45  60 155  85  20 250 195 175]


In [39]:
print(np.mean(arr))

24.4


In [40]:
print(np.median(arr))

23.5


In [41]:
print(np.std(arr))

13.828955130450023


In [42]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [43]:
print(arr[6])
print(arr[7])

4
50


In [44]:
print(np.min(arr))
print(np.max(arr))

4
50


In [45]:
# yes the outputs do match the previous step!!

In [46]:
# --- 3.2: 2D NumPy Arrays ---
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
array = np.array(matrix)
print(array)

[[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]


In [47]:
np.shape(array)

(3, 4)

In [48]:
# There are 3 rows and 4 columns! As seen by the previous output.

In [49]:
print(array[:,3])

[ 9  3 11]


In [50]:
print(array[1])

[ 8 21 14  3]


In [51]:
print(array*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [52]:
print(np.mean(array[0,:]))
print(np.mean(array[1,:]))
print(np.mean(array[2,:]))

10.75
11.5
12.25


In [53]:
print(np.mean(array))

11.5


In [54]:
print(np.max(array[0,:]))
print(np.min(array[0,:]))
print(np.max(array[1,:]))
print(np.min(array[1,:]))
print(np.max(array[2,:]))
print(np.min(array[2,:]))

17
5
21
3
19
6


In [55]:
flatten_array = array.flatten()
print(flatten_array)
print(array)
print(np.shape(flatten_array)) # The new shape is (12,) which happened b/c all the nested array was 'flattened' into a 1D array.

[ 5 12 17  9  8 21 14  3  6 13 19 11]
[[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]
(12,)


In [56]:
max_index = np.argmax(flatten_array)
min_index = np.argmin(flatten_array)
print(max_index)
print(min_index)

5
7


In [57]:
max_matrix = np.unravel_index(max_index, array.shape)
min_matrix = np.unravel_index(min_index, array.shape)
print(max_matrix)
print(min_matrix)

(np.int64(1), np.int64(1))
(np.int64(1), np.int64(3))


In [58]:
cond = array > 15
new_array = array[cond]
print(new_array)

[17 21 19]


In [59]:
sorted_array = np.sort(array)
print(sorted_array)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [60]:
# --- 4: Prime Star Systems ---
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

In [61]:
def is_prime(x):
    if x < 2:
        return False
    for i in range(2, int(x**0.5) + 1):
        if x % i == 0:
            return False
    return True

def prime_rows(arr):
    prime_mask = np.array([[is_prime(x) for x in row] for row in arr])
    return arr[prime_mask.any(axis=1)]

print(prime_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [62]:
# --- 5.1 ---
n = 8
def zeros(x):
    return np.zeros((n,n), dtype=int)
zero_arr = zeros(1)
print(zero_arr)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [63]:
# --- 5.2 ----
for row in range(n): 
    if row % 2 == 0:
        for col in range(n):
            if col % 2 == 0:
                zero_arr[row, col] = 1
print(zero_arr)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [64]:
for row in range(n):
    for col in range(n):
        if row % 2 == 0:
            if col % 2 == 0:
                zero_arr[row, col] = 1
            else:
                zero_arr[row, col] = 0
        else:
            if col % 2 == 0:
                zero_arr[row, col] = 0
            else:
                zero_arr[row, col] = 1
print(zero_arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [65]:
n = 8
def zeross(x):
    return np.zeross((n,n), dtype=int)
zero_array = zeros(1)

for row in range(n):
    for col in range(n):
        if row % 2 == 0:
            if col % 2 == 0:
                zero_array[row, col] = 0
            else:
                zero_array[row, col] = 1
        else:
            if col % 2 == 0:
                zero_array[row, col] = 1
            else:
                zero_array[row, col] = 0
print(zero_array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [66]:
# --- 6: The Expanding Universe ---
def spacing(string_num, spaces):
    string_num = np.array(string_num)
    result = []
    for x in string_num:
        new_string = ''
        for i in range(len(x)):
            new_string += x[i]
            if i != len(x) - 1:
                new_string += ' ' * spaces
        result.append(new_string)
    return np.array(result)

universe = np.array(['galaxy', 'clusters'])
print(spacing(universe, 1))
print(spacing(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [67]:
# --- 7: Second-Brightest Star ---
np.random.seed(123)
stars = np.random.randint(500, 2000, (5,5))

def secondDimmest(arr):
    result = []

    for row in arr:
        max_val = -np.inf
        second_max = -np.inf
        for val in row:
            if val > max_val: 
                second_max = max_val
                max_val = val
            elif val > second_max:
                second_max = val
        result.append(second_max)
    return np.array(result)

print(stars)
print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
